/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusRouteImport } from './routes/bus'
import { Route as ChaosRouteImport } from './routes/chaos'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as TracesRouteImport } from './routes/traces'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaosRoute = ChaosRouteImport.update({
  id: '/chaos',
  path: '/chaos',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/chaos': typeof ChaosRoute
  '/incidents': typeof IncidentsRoute
  '/mesh': typeof MeshRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/regions': typeof RegionsRoute
  '/traces': typeof TracesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/chaos': typeof ChaosRoute
  '/incidents': typeof IncidentsRoute
  '/mesh': typeof MeshRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/regions': typeof RegionsRoute
  '/traces': typeof TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/chaos': typeof ChaosRoute
  '/incidents': typeof IncidentsRoute
  '/mesh': typeof MeshRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/regions': typeof RegionsRoute
  '/traces': typeof TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus'
    | '/chaos'
    | '/incidents'
    | '/mesh'
    | '/orders'
    | '/platform'
    | '/regions'
    | '/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/chaos'
    | '/incidents'
    | '/mesh'
    | '/orders'
    | '/platform'
    | '/regions'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/bus'
    | '/chaos'
    | '/incidents'
    | '/mesh'
    | '/orders'
    | '/platform'
    | '/regions'
    | '/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusRoute: typeof BusRoute
  ChaosRoute: typeof ChaosRoute
  IncidentsRoute: typeof IncidentsRoute
  MeshRoute: typeof MeshRoute
  OrdersRoute: typeof OrdersRoute
  PlatformRoute: typeof PlatformRoute
  RegionsRoute: typeof RegionsRoute
  TracesRoute: typeof TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chaos': {
      id: '/chaos'
      path: '/chaos'
      fullPath: '/chaos'
      preLoaderRoute: typeof ChaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusRoute: BusRoute,
  ChaosRoute: ChaosRoute,
  IncidentsRoute: IncidentsRoute,
  MeshRoute: MeshRoute,
  OrdersRoute: OrdersRoute,
  PlatformRoute: PlatformRoute,
  RegionsRoute: RegionsRoute,
  TracesRoute: TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
